version: '3.8'

services:

  server:
    image: coutomarcos/crud-grpc:latest
    container_name: server
    network_mode: host
    env_file:
      - env/server.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    network_mode: host
    env_file:
      - env/postgres.env

  pgadmin:
    image: dpage/pgadmin4
    network_mode: host
    container_name: pgadmin
    env_file:
      - env/pgadmin.env
    ports:
      - 5433:5433
    depends_on:
      - postgres